[package]
name = "ocos-capability"
description = "Compute node capability descriptors for Open Compute OS"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true

[lints]
workspace = true
